### ISSUE TITLE
希望SDK尽快支持模拟器

### ISSUE THREAD

**Issue by jaunce** [CCVideo/Live_iOS_Play_SDK#10]
希望SDK尽快支持模拟器，不然太尴尬了，一旦引入sdk，我想用模拟器做不同机型屏幕适配都不行，而且很多开发调试工具是模拟器上用的，比如hot reload，现在全不能用了

**Comment by Clark-new** [comment]
可以找客服人员提供模拟器SDK,3.9.1开始我们将支持模拟器cocopod集成
