### ISSUE TITLE
3.7.0 CCBundle 导致上传app store失败

### ISSUE THREAD

**Issue by yelin1597532** [CCVideo/Live_iOS_Play_SDK#12]
3.7.0的CCBundle的info.plist里有CFBundleExecutable字段，但是并没有可执行文件，导致上传app store时过不了检查，提交市场失败

**Comment by Clark-new** [comment]
直接将CCBundle的info.plist里有CFBundleExecutable删除即可,另外使用我们能SDK文件里面的包,不要使用demo里面的SDK
