### ISSUE TITLE
强烈建议增加cocoapod集成，手动集成太麻烦了

### ISSUE THREAD

**Issue by jaunce** [CCVideo/Live_iOS_Play_SDK#7]
cc demo项目用了pch，如果想集成cc demo中的UI，导入到自己的项目中会很麻烦，需要把头文件一一对应import进去，现在很少有项目在用pch，apple很早已经不推荐用pch

**Comment by Clark-new** [comment]
已经支持cocopod 了 文档也标注了集成方式 感谢您的建议
